name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"
  push:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

jobs:
  debug-builds:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Retrieve Commit Info
        run: |
          cd .github
          curl https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} > commit.json
          cd ..

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Git Configuraion
        run: |
          git config --global user.name "libretube-bot"
          git config --global user.email "libretube@proton.me"
          git config --global credential.helper store
          echo "https://libretube-bot:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Compile
        run: |
          ./gradlew assembleRelease

      - name: Upload to Archive
        continue-on-error: true
        run: |
          mv .github/uploader.py .
          echo "GH_REPO = '${{ github.repository }}'" > config_file.py
          git clone --filter=blob:none https://github.com/libre-tube/NightlyBuilds nightly
          rm -rf nightly/*.apk
          mv app/build/outputs/apk/debug/*.apk nightly/
          cd nightly
          python ../uploader.py
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: nightly/*.apk

